### ISSUE TITLE
Enhance workspace with precommit tools

### ISSUE THREAD

**Issue by Jefiozie** [validointi/validointi#19]
To be consistent with code guidelines, line breaks formatting add a couple of tools

- [x] wireit
- [ ] prettier
- [x]  eslint rules
- [ ]  css rules?
- [ ]  husky
- [ ]  lint staged

**Comment by SanderElias** [comment]
Let us first intorduce wireIt to keep the think manageable to begin with!

**Comment by Jefiozie** [comment]
Wireit is implemented

**Comment by Jefiozie** [comment]
eslint is impleented via #26
