### ISSUE TITLE
Deployment of app

### ISSUE THREAD

**Issue by Jefiozie** [validointi/validointi#20]
Let's deploy the app as an example to x place. Of course need to have published our lib to npm

**Comment by SanderElias** [comment]
Github pages?

**Comment by Jefiozie** [comment]
Sure, I'm happy to do this, maybe we can make an organization or something if we feel the need to decouple it from my profile?

**Comment by SanderElias** [comment]
No rush

**Comment by Jefiozie** [comment]
This issue can be closed as we have deployed a documentation page and created an organization.
